### ISSUE TITLE
None Type object does not support item Assignment 

### ISSUE THREAD

**Issue by tawabshakeel** [explainX/explainx#1]
library not working on Gradient Boosting Regressor Model 

![image](https://user-images.githubusercontent.com/24355495/85059951-dfce5c80-b1bd-11ea-82a3-5b6fe44fe96c.png)

![image](https://user-images.githubusercontent.com/24355495/85060015-f4aaf000-b1bd-11ea-8351-fbdb69fe665f.png)

**Comment by ms8909** [comment]
Currently, the library does not support GradientBoostingRegressor. We will add this model in the next release.

**Comment by ms8909** [comment]
Support for GradientBoostingRegressor added in the library. Please have a look and let us know if you still experiencing the error. I am closing this issue for now.
