### ISSUE TITLE
Unicode Decode Error in explain.ai()

### ISSUE THREAD

**Issue by AMChierici** [explainX/explainx#12]
When running the 'get started' example, I get a UnicodeDecodeError. See the attached screenshot.
<img width="1173" alt="Screen Shot 2020-08-29 at 9 47 35 AM" src="https://user-images.githubusercontent.com/8417024/91631803-be1efc00-e9dc-11ea-8e61-38bd4a7f79d8.png">
<img width="1173" alt="Screen Shot 2020-08-29 at 9 47 42 AM" src="https://user-images.githubusercontent.com/8417024/91631804-bf502900-e9dc-11ea-9315-c27b56effcb0.png">

**Comment by ms8909** [comment]
Csn you please share the version of SHAP that you have installed?

**Comment by ms8909** [comment]
I think xgboost version you have installed is not compatible with SHAP.  Try to run this.

pip install xgboost==1.0.2

**Comment by AMChierici** [comment]
> Csn you please share the version of SHAP that you have installed?

I had 0.34.0 for the shap package.

> I think xgboost version you have installed is not compatible with SHAP. Try to run this.
> 
> pip install xgboost==1.0.2

I had 1.2.0 as xgboost.

I created a new environment, installed again explainx, and xgboost 1.0.2. It now works, thanks!

BTW -- you might want to update your 'get started' example by adding an `import xgboost` and an `import matplotlib`, or the installation of explainx with those two dependencies.
