### ISSUE TITLE
ExpainX is getting freeze with high dimensional data

### ISSUE THREAD

**Issue by rezacsedu** [explainX/explainx#17]
As the title says, ExpainX is getting freeze with high dimensional data. In particular, I have a dataset that has 10K samples. The number of features is about 8K. When I deploy the model and try to access the interface, the webpage is getting non-responsive.

**Comment by rab657** [comment]
The interface and techniques do not support such high-dimensional dataset - a high number of rows is okay but such a high number of features will currently not work. 

We will keep the issue open and work on a solution. We will also publish developer guidelines soon and so feel free to address this issue.

**Comment by rezacsedu** [comment]
@rab657, thank you.
