### ISSUE TITLE
Classification and regression metrices are mixed up, it seems!

### ISSUE THREAD

**Issue by rezacsedu** [explainX/explainx#19]
Re: calculate_metrics.py, it seems regression metrics such as MAE, MSE, R^2 have been placed mistakenly in the  classification_metrics method. Is it intentional? In particular, I'm talking about the following lines: 

       `       
       # MAE
        mae = mean_absolute_error(y_test, model_predict) 

        # MSE
        mse = mean_squared_error(y_test, model_predict)

        # RMS
        rms = sqrt(mse) 
       `

**Comment by ms8909** [comment]
Thanks for pointing out. This part of the code is still under progress. I'll update up once we finish this.

**Comment by rab657** [comment]
Metrics updated.
