### ISSUE TITLE
Adding a tab to show model performance

### ISSUE THREAD

**Issue by rezacsedu** [explainX/explainx#25]
How about having a feature/tab to visualize model performance in terms of metrics (f1, precision, recall, MSE, MAE, R^2, etc.), confusing matrix, AUC, ROC, etc.? 

A reference example could be a similar functinality provided by explainerdashboard (link: https://github.com/oegedijk/explainerdashboard)

![image](https://user-images.githubusercontent.com/14220009/99047295-4a7c9c00-2594-11eb-9242-1c28bdfa69e7.png)

**Comment by rab657** [comment]
Hi! 

Thank you for this. 
This is definitely in our pipeline and we are building this module along with the monitoring part. 

Will update this soon.
