### ISSUE TITLE
dash app running on http://0.0.0.0:8080 is not working please help me

### ISSUE THREAD

**Issue by epayush** [explainX/explainx#33]
**I just try explainx in python or django also**

```
from explainx import *
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X_data, Y_data = explainx.dataset_heloc()
X_train, X_test, Y_train, Y_test = train_test_split(X_data, Y_data, test_size=0.3, random_state=0)
# Train a RandomForest Model
model = RandomForestClassifier()
model.fit(X_train, Y_train)
explainx.ai(X_test, Y_test, model, model_name="randomforest")
```

it gives a running server like :- **dash app running on http://0.0.0.0:8080**
but when i click on this server, this server is not working

image for reference:-

![ERRORCapture](https://user-images.githubusercontent.com/77789061/106275275-8e11a880-625b-11eb-8b39-4c66b28a5e47.PNG)

please help me.

**Comment by epayush** [comment]
That both server is nor working

```
Running on http://0.0.0.0:8080/
Debugger PIN: 624-926-050
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Running on http://0.0.0.0:62731/
Debugger PIN: 330-309-028
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

```
**can you please help me**

**Comment by tawabshakeel** [comment]
Our team Is working on the issue. This will be resolved soon.

**Comment by epayush** [comment]
Thanks Sir . I will wait for Your response @tawabshakeel

**Comment by epayush** [comment]
@tawabshakeel Sir, Is there any solution about that server i also try it into **python** or **jupyter notebook** its not working yet.
**please help me**

**Comment by tawabshakeel** [comment]
@epayush , Our team is working on the Issue . This will be resolved by the end of this week.
