### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by ravijoe** [explainX/explainx#34]
I am not able to install or run explainx. even the default given code on your repo is not working. Just copy  the default code on the library's landing page and paste on google colab it won't run

**Comment by tawabshakeel** [comment]
Thanks, @ravijoe for mentioning the error. Explainx is not yet supported on google colab. Our team is working on the support.
But If you want to use it you can use the Explainx on AWS Sagemaker Notebooks.
Here is the link to Installing the library on AWS Sagemaker https://www.youtube.com/watch?v=A_0FZvP4nJA&ab_channel=explainXAI

**Comment by ravijoe** [comment]
What about installing it locally? Can't I do that also

**Comment by tawabshakeel** [comment]
If you are working on Mac OS then you can run locally but In the case of Windows, it will be resolved by the end of this week.

**Comment by ravijoe** [comment]
No I'm running on Ubuntu

**Comment by tawabshakeel** [comment]
Ubuntu and Windows are facing some issues they will be resolved by the end of the week.

**Comment by ravijoe** [comment]
Ok got it. And are there also issues while using this in kaggle notebooks ?
M facing issues while running this in kaggle also

**Comment by rab657** [comment]
Yes - Kaggle has the same issue as Google Colab as they both are using their own notebook environment. 
We are working on resolving this, will update in a few weeks.

**Comment by ravijoe** [comment]
Ok, thanks for the update! Hope you fix all these issues. Really looking
forward using this library.

**Comment by ravijoe** [comment]
I''m yet to check the changes
