### ISSUE TITLE
Type error occurs when there is no header in DataFrame

### ISSUE THREAD

**Issue by MisooKim** [explainX/explainx#35]
When using example codes in README.md, 
I input the DataFrame without a header, so the columns' names set as an Integer type.

So the bugs occurred in the following codes in dashboard.py because the col is not String.

`original_variables = [col for col in df.columns if '_impact' in col]`
`self.callback_input = [Input(f + '_slider', 'value') for f in self.param["columns"]]`

I fixed this bug by modifying the below code at 225 line in explain.py.

`self.param["columns"] = df.columns.astype(str)`

I fixed this bug by adding the below code at 230 line in explain.py.
`self.df_final.columns = self.df_final.columns.astype(str)`

**Comment by tawabshakeel** [comment]
@MisooKim Please update the code and create a Merge Request. It will be Merge with the master Branch after code review.

Thanks for pointing out the issue.
