### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by varunbanda** [explainX/explainx#36]
I'm getting the following error while trying to install explainx on Windows.
[Screenshot](https://imgur.com/a/OHBPNUu)

`Running setup.py install for cvxopt ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\explainx\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\banda\\AppData\\Local\\Temp\\pip-install-qhfmfesn\\cvxopt\\setup.py'"'"'; __file__='"'"'C:\\Users\\banda\\AppData\\Local\\Temp\\pip-install-qhfmfesn\\cvxopt\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\banda\AppData\Local\Temp\pip-record-4si3fvdc\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\explainx\include\site\python3.8\cvxopt'
         cwd: C:\Users\banda\AppData\Local\Temp\pip-install-qhfmfesn\cvxopt\
    Complete output (20 lines):
    running install
    running build
    running build_py
    package init file 'src\python\__init__.py' not found (or not a regular file)
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\cvxopt
    copying src\python\_version.py -> build\lib.win-amd64-3.8\cvxopt
    UPDATING build\lib.win-amd64-3.8\cvxopt/_version.py
    set build\lib.win-amd64-3.8\cvxopt/_version.py to '1.2.4'
    running build_ext
    building 'base' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\src
    creating build\temp.win-amd64-3.8\Release\src\C
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Id:\explainx\include -IC:\Python\Python387\include -IC:\Python\Python387\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsrc/C/base.c /Fobuild\temp.win-amd64-3.8\Release\src/C/base.obj
    base.c
    c1: fatal error C1083: Cannot open source file: 'src/C/base.c': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\explainx\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\banda\\AppData\\Local\\Temp\\pip-install-qhfmfesn\\cvxopt\\setup.py'"'"'; __file__='"'"'C:\\Users\\banda\\AppData\\Local\\Temp\\pip-install-qhfmfesn\\cvxopt\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\banda\AppData\Local\Temp\pip-record-4si3fvdc\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\explainx\include\site\python3.8\cvxopt' Check the logs for full command output.`

**Comment by tawabshakeel** [comment]
Try to Install visual studio build tools for C++ 
https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by ms8909** [comment]
To run explainx on windows, you need to install visual studio using the link below.

https://visualstudio.microsoft.com/visual-cpp-build-tools/
