### ISSUE TITLE
Facing problem during installation of explainx in google colab notebook

### ISSUE THREAD

**Issue by chinu90** [explainX/explainx#42]
![image](https://github.com/explainX/explainx/assets/124143389/359dcb5c-8f84-4366-8b5a-d24f3fa8bf6e)

**Comment by mi3law** [comment]
Thank you for opening this issue.

I tried pip install explainx on my windows command prompt and got a similar install error, though mine was related to numpy only (see here ![WindowsTerminal - 761 - ALI-SPECTRE](https://github.com/explainX/explainx/assets/84152592/0399ab94-d3ac-47a6-b4fa-9f179cc2adef))

We'll resolve this and get back to you.
