### ISSUE TITLE
xgboost error

### ISSUE THREAD

**Issue by saadpolo** [explainX/explainx#8]
<img width="1040" alt="Screenshot 2020-07-07 at 9 54 08 PM" src="https://user-images.githubusercontent.com/66383302/86865127-6fb84580-c09c-11ea-9efe-c00a870759f0.png">

**Comment by ms8909** [comment]
You have 32-bit Python installed on your computer that only supports 64-bit Python. Please install 64-bit python from https://www.python.org/downloads/ and try again.

**Comment by ms8909** [comment]
After installing 64-bit python, please run the following in a terminal.

_**pip uninstall explainx
pip install explainx**_
